### ISSUE TITLE
Draft Schedule

### ISSUE THREAD

**Issue by ivanov** [numfocus/summit2019-scheduling#1]
On the NumFocus Summit planning call today, we were trying to brainstorm how to increase participation from projects and getting them to look and comment on the schedule as it is now. @bryevdv suggested that having a link to it from here would help (as would having a group we could ping):

https://docs.google.com/spreadsheets/d/1u0NWbFcwNrw-bPz_Pu1wWOIG-LJf5aL6q3oyHlclptM/edit

**Comment by Dr-G** [comment]
The schedule is posted here: https://numfocus.org/summit2019#schedule
